//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transactions
    {
        public int Id { get; set; }
        [Display(Name = "Transaction Date")]
        public System.DateTime TransactionDate { get; set; }
        [Display(Name = "Transaction Type")]
        public int transactiontype_id { get; set; }
        [Display(Name = "Amount")]
        public double amount { get; set; }
        [Display(Name = "Client Origin Code")]
        public int clientorg_Id { get; set; }
        [Display(Name = "Old Balance Origin")]
        public Nullable<double> oldbalanceorg { get; set; }
        [Display(Name = "New Balance Origin")]
        public Nullable<double> newbalanceorg { get; set; }
        [Display(Name = "Client Destination Code")]
        public int clientdest_Id { get; set; }
        [Display(Name = "Old Balance Destination")]
        public Nullable<double> oldbalancedest { get; set; }
        [Display(Name = "New Balance Destination")]
        public Nullable<double> newbalancedest { get; set; }
        public Nullable<int> isfraud { get; set; }
        public int usercreation_id { get; set; }
        public Nullable<int> usermarkfraud_id { get; set; }
        public Nullable<System.DateTime> frauddate { get; set; }


        [Display(Name = "Client Origin Code")]
        public virtual Clients Clients { get; set; }
        [Display(Name = "Client Destination Code")]
        public virtual Clients Clients1 { get; set; }
        [Display(Name = "Transaction Type")]
        public virtual Transactiontypes Transactiontypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
